name: Publish package to npm
on: push
jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Bun 1.0.6
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.6
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dabolus'
      - name: Install dependencies
        run: bun install
      - name: Run codegen
        run: bun run codegen
      - name: Build package
        run: bun run build
      - name: Update package version
        run: |
          git config --global user.name 'Giorgio Garasto'
          git config --global user.email 'dabolus@users.noreply.github.com'
          npm version minor -m 'chore: bump version to %s [skip ci]'
          git push --follow-tags
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
